### ISSUE TITLE
Add JIRA link as channel topic

### ISSUE THREAD

**Issue by fsergot** [Ullink/jira-slackit#1]
When creating a new channel, the channel topic should be set with the JIRA issue URL, this would allow a quick jump back to JIRA.

![image](https://cloud.githubusercontent.com/assets/21310387/18343630/7eadda5a-75b4-11e6-89cb-a21b82fd0f56.png)

**Comment by arnaudj** [comment]
Fixed thanks to @gonchik in #8

**Comment by gonchik** [comment]
Well, I can't close it.

Looks like time work on own fork :)

**Comment by dfev77** [comment]
This does not seem to work anymore, the topic is not added.

Jira v8.13.10#813010-sha1:156ab00
Slackit I suppose is the latest version
